data:
  token_sequence_loader:
    type: "fasta"
    fasta_path: "/workspace/data/dataset/uniref50_3M_length_512.fasta"
    max_sequence_length: 512
  activations_harvester:
    llms:
      - hf_model_name: Rostlab/prot_t5_xl_uniref50
        base_architecture_name: T5ForConditionalGeneration
    harvesting_batch_size: 64
    cache_mode: "no_cache"
  activations_shuffle_buffer_size: 400_000
crosscoder:
  n_latents: 8192
  k: 32
train:
  batch_size: 512
  num_steps: 2_519_889
  log_every_n_steps: 10
  topk_style: "batch_topk"
  dead_latents_threshold_n_examples: 5_000_000
  k_aux: 512 # heuristic model_dim / 2
  lambda_aux: 0.03125 # 1/32
experiment_name: "crosscoder_l8192_k32"
wandb:
  entity: "sohrab-train"
  project: "crosscoders-protT5"
base_save_dir: "/workspace/data/checkpoints"
cache_dir: "/workspace/data/hf_home/"
hookpoints: [
  "encoder.blocks.1.hook_resid_post",
  "encoder.blocks.2.hook_resid_post",
  "encoder.blocks.3.hook_resid_post",
  "encoder.blocks.4.hook_resid_post",
  "encoder.blocks.5.hook_resid_post",
  "encoder.blocks.6.hook_resid_post",
  "encoder.blocks.7.hook_resid_post",
  "encoder.blocks.8.hook_resid_post",
  "encoder.blocks.9.hook_resid_post",
  "encoder.blocks.10.hook_resid_post",
  "encoder.blocks.11.hook_resid_post",
  "encoder.blocks.12.hook_resid_post",
  "encoder.blocks.13.hook_resid_post",
  "encoder.blocks.14.hook_resid_post",
  "encoder.blocks.15.hook_resid_post",
  "encoder.blocks.16.hook_resid_post",
  "encoder.blocks.17.hook_resid_post",
  "encoder.blocks.18.hook_resid_post",
  "encoder.blocks.19.hook_resid_post",
  "encoder.blocks.20.hook_resid_post",
  "encoder.blocks.21.hook_resid_post",
  "encoder.blocks.22.hook_resid_post",
  "encoder.blocks.23.hook_resid_post",
  "encoder.blocks.24.hook_resid_post"
]